<?php

namespace projecto\KikoloBundle\Repository;

/**
 * AnuncianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnuncianteRepository extends \Doctrine\ORM\EntityRepository
{
}
