<?php

namespace projecto\KikoloBundle\Repository;

/**
 * KikoloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KikoloRepository extends \Doctrine\ORM\EntityRepository
{
}
