<?php

namespace projecto\KikoloBundle\Repository;

/**
 * TipoAnuncioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAnuncioRepository extends \Doctrine\ORM\EntityRepository
{
}
