<?php

namespace projecto\KikoloBundle\Repository;

/**
 * UploadsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadsRepository extends \Doctrine\ORM\EntityRepository
{
}
