kikolo_index:
    path:     /
    defaults: { _controller: "projectoKikoloBundle:Kikolo-cadastro-anuncio:index" }
    methods:  GET

kikolo_show:
    path:     /{id}/show
    defaults: { _controller: "projectoKikoloBundle:Kikolo-cadastro-anuncio:show" }
    methods:  GET

kikolo_new:
    path:     /new
    defaults: { _controller: "projectoKikoloBundle:Kikolo-cadastro-anuncio:new" }
    methods:  [GET, POST]

kikolo_edit:
    path:     /{id}/edit
    defaults: { _controller: "projectoKikoloBundle:Kikolo-cadastro-anuncio:edit" }
    methods:  [GET, POST]

kikolo_delete:
    path:     /{id}/delete
    defaults: { _controller: "projectoKikoloBundle:Kikolo-cadastro-anuncio:delete" }
    methods:  DELETE
