projecto\KikoloBundle\Entity\Uploads:
    type: entity
    table: null
    repositoryClass: projecto\KikoloBundle\Repository\UploadsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        path:
            type: string
            length: 255
        alt:
            type: string
            length: 255
    lifecycleCallbacks: {  }
